# --------------------------------------------------
# Live reload
# --------------------------------------------------
include current-theme.conf

# --------------------------------------------------
# Font
# --------------------------------------------------
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# --------------------------------------------------
# Cursor
# --------------------------------------------------
cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0

# --------------------------------------------------
# Window
# --------------------------------------------------
background_opacity 1.0
window_padding_width 0
hide_window_decorations yes
dynamic_background_opacity no

# --------------------------------------------------
# Shell
# --------------------------------------------------
shell bash --norc --noprofile -c "$HOME/.local/bin/ts-create.sh $PWD"

# --------------------------------------------------
# TERM
# --------------------------------------------------
term xterm-256color

# --------------------------------------------------
# Colors
# --------------------------------------------------
foreground              #d3dbe3
background              #181b1e
selection_foreground    #d3dbe3
selection_background    #2d333b

cursor                  #d3dbe3
cursor_text_color       #181b1e

color0  #181b1e
color1  #ff7a93
color2  #9cee82
color3  #ffc777
color4  #7da6ff
color5  #d7a1f9
color6  #5de4c7
color7  #d3dbe3

color8  #373e47
color9  #ff7a93
color10 #9cee82
color11 #ffc777
color12 #7da6ff
color13 #d7a1f9
color14 #5de4c7
color15 #ffffff

# --------------------------------------------------
# Mouse
# --------------------------------------------------
mouse_hide_wait 0.0
copy_on_select no

# --------------------------------------------------
# Performance
# --------------------------------------------------
repaint_delay 10
input_delay 3
sync_to_monitor yes

# --------------------------------------------------
# Clipboard
# --------------------------------------------------
clipboard_control write-clipboard write-primary read-clipboard read-primary

# --------------------------------------------------
# Enable graphics support
# --------------------------------------------------
allow_remote_control yes
